export const airports = [
  { value: 'TPE', label: 'TPE - Taipei Taoyuan International' },
  { value: 'NRT', label: 'NRT - Narita International Airport, Tokyo' },
  { value: 'HND', label: 'HND - Haneda Airport, Tokyo' },
  { value: 'KIX', label: 'KIX - Kansai International Airport, Osaka' },
  { value: 'ICN', label: 'ICN - Incheon International Airport, Seoul' },
  { value: 'BKK', label: 'BKK - Suvarnabhumi Airport, Bangkok' },
  { value: 'DMK', label: 'DMK - Don Mueang International Airport, Bangkok' },
  { value: 'SIN', label: 'SIN - Singapore Changi Airport' },
  { value: 'HKG', label: 'HKG - Hong Kong International Airport' },
  { value: 'KUL', label: 'KUL - Kuala Lumpur International Airport' },
  { value: 'JFK', label: 'JFK - John F. Kennedy International Airport, New York' },
  { value: 'LAX', label: 'LAX - Los Angeles International Airport' },
  { value: 'LHR', label: 'LHR - London Heathrow Airport' },
  { value: 'CDG', label: 'CDG - Charles de Gaulle Airport, Paris' },
  { value: 'AMS', label: 'AMS - Amsterdam Airport Schiphol' },
  { value: 'FRA', label: 'FRA - Frankfurt Airport' },
  { value: 'SYD', label: 'SYD - Sydney Kingsford Smith Airport' },
  { value: 'YYZ', label: 'YYZ - Toronto Pearson International Airport' },
  { value: 'YVR', label: 'YVR - Vancouver International Airport' },
  { value: 'DXB', label: 'DXB - Dubai International Airport' },
];
