import type { Flight } from './types';

export const mockFlights: Flight[] = [
  // Japan
  {
    id: '1',
    airline: 'Starlux Airlines',
    flightNumber: 'JX802',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-09-10T08:30:00' },
    arrival: { airport: 'NRT', city: 'Tokyo', time: '2024-09-10T12:45:00' },
    duration: '3h 15m',
    price: 350,
    destinationCountry: 'Japan',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '2',
    airline: 'EVA Air',
    flightNumber: 'BR198',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-09-12T09:00:00' },
    arrival: { airport: 'NRT', city: 'Tokyo', time: '2024-09-12T13:15:00' },
    duration: '3h 15m',
    price: 380,
    destinationCountry: 'Japan',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '3',
    airline: 'China Airlines',
    flightNumber: 'CI100',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-09-15T09:30:00' },
    arrival: { airport: 'NRT', city: 'Tokyo', time: '2024-09-15T13:45:00' },
    duration: '3h 15m',
    price: 365,
    destinationCountry: 'Japan',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '4',
    airline: 'Peach Aviation',
    flightNumber: 'MM620',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-09-20T07:50:00' },
    arrival: { airport: 'KIX', city: 'Osaka', time: '2024-09-20T11:20:00' },
    duration: '2h 30m',
    price: 280,
    destinationCountry: 'Japan',
    bookingUrl: 'https://www.google.com/flights',
  },
  // South Korea
  {
    id: '5',
    airline: 'Korean Air',
    flightNumber: 'KE186',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-10-05T13:25:00' },
    arrival: { airport: 'ICN', city: 'Seoul', time: '2024-10-05T17:00:00' },
    duration: '2h 35m',
    price: 320,
    destinationCountry: 'South Korea',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '6',
    airline: 'Asiana Airlines',
    flightNumber: 'OZ712',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-10-08T12:55:00' },
    arrival: { airport: 'ICN', city: 'Seoul', time: '2024-10-08T16:30:00' },
    duration: '2h 35m',
    price: 310,
    destinationCountry: 'South Korea',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '7',
    airline: 'Tway Air',
    flightNumber: 'TW668',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-10-11T11:00:00' },
    arrival: { airport: 'ICN', city: 'Seoul', time: '2024-10-11T14:35:00' },
    duration: '2h 35m',
    price: 250,
    destinationCountry: 'South Korea',
    bookingUrl: 'https://www.google.com/flights',
  },
   // Thailand
  {
    id: '8',
    airline: 'Thai Airways',
    flightNumber: 'TG635',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-11-01T20:05:00' },
    arrival: { airport: 'BKK', city: 'Bangkok', time: '2024-11-01T23:05:00' },
    duration: '4h 0m',
    price: 290,
    destinationCountry: 'Thailand',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '9',
    airline: 'EVA Air',
    flightNumber: 'BR211',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-11-03T09:00:00' },
    arrival: { airport: 'BKK', city: 'Bangkok', time: '2024-11-03T12:00:00' },
    duration: '4h 0m',
    price: 315,
    destinationCountry: 'Thailand',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '10',
    airline: 'Thai Lion Air',
    flightNumber: 'SL395',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-11-07T10:10:00' },
    arrival: { airport: 'DMK', city: 'Bangkok', time: '2024-11-07T13:10:00' },
    duration: '4h 0m',
    price: 220,
    destinationCountry: 'Thailand',
    bookingUrl: 'https://www.google.com/flights',
  },
  // Vietnam
  {
    id: '11',
    airline: 'Vietnam Airlines',
    flightNumber: 'VN571',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-09-25T13:35:00' },
    arrival: { airport: 'HAN', city: 'Hanoi', time: '2024-09-25T15:45:00' },
    duration: '3h 10m',
    price: 260,
    destinationCountry: 'Vietnam',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '12',
    airline: 'VietJet Air',
    flightNumber: 'VJ941',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-09-28T19:00:00' },
    arrival: { airport: 'SGN', city: 'Ho Chi Minh City', time: '2024-09-28T21:30:00' },
    duration: '3h 30m',
    price: 210,
    destinationCountry: 'Vietnam',
    bookingUrl: 'https://www.google.com/flights',
  },
  // Singapore
  {
    id: '13',
    airline: 'Singapore Airlines',
    flightNumber: 'SQ877',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-10-20T14:10:00' },
    arrival: { airport: 'SIN', city: 'Singapore', time: '2024-10-20T18:55:00' },
    duration: '4h 45m',
    price: 400,
    destinationCountry: 'Singapore',
    bookingUrl: 'https://www.google.com/flights',
  },
  {
    id: '14',
    airline: 'Scoot',
    flightNumber: 'TR993',
    departure: { airport: 'TPE', city: 'Taipei', time: '2024-10-22T18:15:00' },
    arrival: { airport: 'SIN', city: 'Singapore', time: '2024-10-22T23:00:00' },
    duration: '4h 45m',
    price: 240,
    destinationCountry: 'Singapore',
    bookingUrl: 'https://www.google.com/flights',
  },
  // Add 15 more to reach ~30
  ...Array.from({ length: 16 }, (_, i) => {
    const countries: Flight['destinationCountry'][] = ['Japan', 'South Korea', 'Thailand', 'Vietnam', 'Singapore'];
    const country = countries[i % countries.length];
    const cities = {
      'Japan': { city: 'Fukuoka', airport: 'FUK' },
      'South Korea': { city: 'Busan', airport: 'PUS' },
      'Thailand': { city: 'Chiang Mai', airport: 'CNX' },
      'Vietnam': { city: 'Da Nang', airport: 'DAD' },
      'Singapore': { city: 'Singapore', airport: 'SIN' },
    };
    const date = new Date(2024, 8 + (i % 3), 1 + i);
    return {
      id: `${15 + i}`,
      airline: ['Starlux Airlines', 'EVA Air', 'China Airlines', 'Korean Air', 'Thai Airways'][i % 5],
      flightNumber: `XX${800 + i}`,
      departure: { airport: 'TPE', city: 'Taipei', time: date.toISOString().replace(/\.\d+Z$/, 'T09:00:00')},
      arrival: { 
        airport: cities[country].airport, 
        city: cities[country].city, 
        time: new Date(date.getTime() + (3 + i%2) * 60 * 60 * 1000).toISOString().replace(/\.\d+Z$/, 'T12:00:00')
      },
      duration: `${3 + i%2}h 30m`,
      price: 200 + i * 10 + Math.floor(Math.random() * 50),
      destinationCountry: country,
      bookingUrl: 'https://www.google.com/flights',
    };
  }),
];
